### ISSUE TITLE
Some Auth0 events not getting pushed to S3

### ISSUE THREAD

**Issue by jaspalgill** [aws-samples/amazon-eventbridge-integration-with-auth0#2]
Thanks for sharing this sample code!
I have integrated auth0 events and pushing it to S3 via event bus, with this I could see SuccessfullSignIn events getting pushed to S3 bucket. 
Other events such as SuccessfullSignUp, SuccessfullSignOutSuccess, SignInFail are not getting streamed.
Is it because PermissionForEventsToInvokeLambda only has permission to "SuccessfullSignIn"?
Also I see the targetIds of all Event bridge rules is "SignInSuccessV1"
```
  PermissionForEventsToInvokeLambda: 
    Type: AWS::Lambda::Permission
    Properties: 
      FunctionName: 
        Ref: "SaveAuth0EventToS3"
      Action: "lambda:InvokeFunction"
      Principal: "events.amazonaws.com"
      SourceArn: 
        Fn::GetAtt: 
          - "SuccessfullSignIn"
          - "Arn"
```
